name: Tests

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.2','8.4']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype, dom, fileinfo, filter, hash, json, mbstring, openssl, pcre, pdo, sqlite, tokenizer
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Setup Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate --force
          php artisan config:cache

      - name: Run tests
        run: php artisan test --compact
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
